config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'posts#index', as: 'home'

  get 'about' => 'pages#about', as: 'about'

  resources :posts do
    resources :comments
  end

  devise_scope :user do
    get '/users/sign_out', to: 'devise/sessions#destroy'
  end  

  root to: "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
    has_many :comments, dependent: :destroy
    validates :title, presence: true, length: {minimum: 5}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!, only: [:edit, :update, :destroy]
    before_action :set_post
    before_action :set_comment, only: [:edit, :update, :destroy]
  
    def create
        @comment = @post.comments.create(comment_params)
        redirect_to post_path(@post)
    end
  
    def edit
        
    end
  
    def update
        if @comment.update(comment_params)
            redirect_to post_path(@post)
        else
            render :edit
        end
    end
  
    def destroy
        @comment.destroy
        redirect_to post_path(@post)
    end
  
    private 
  
    def set_post
        @post = Post.find(params[:post_id])
    end
  
    def set_comment
        @comment = @post.comments.find(params[:id])
    end
  
    def comment_params
        params.require(:comment).permit(:username, :body)
    end
  end
  

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def about
        @heading = 'Сторінка про нас'
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
    def index
        @post = Post.all
    end

    def new
        @post = Post.new
    end

    def show
        @post = Post.find(params[:id])
    end

    def edit
        @post = Post.find(params[:id])
    end

    def update
        @post = Post.find(params[:id])

        if @post.update(post_params)
            redirect_to @post
        else
            flash[:error1] = @post.errors.full_messages.first
            flash[:error2] = @post.errors.full_messages.second
            redirect_to edit_post_path
        end
    end

    def destroy
        @post = Post.find(params[:id])

        @post.destroy
        redirect_to posts_path
    end

    def create
        # render plain: params[:post].inspect
        @post = Post.new(post_params)

        if @post.save
            redirect_to @post
        else
            flash[:error1] = @post.errors.full_messages.first
            flash[:error2] = @post.errors.full_messages.second
            redirect_to new_post_path
        end
    end

    private def post_params
        params.require(:post).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/edit.html.erb
<h2>Редагування коментарю</h2>

<%= form_for [@post, @comment] do |f| %>
    <p>
        Користувач<br>
            <%= f.text_field :username, class: "form-control" %>
    </p>
    <p>
        Текст коментаря<br>
            <%= f.text_area :body, class: "form-control" %>
    </p>

    <%= f.submit "Зберегти", class: "btn btn-success" %>
<% end %>

app/views/include/main/_notification.html.erb
<% if notice %>
    <p class="notice alert-success"><%= notice %></p>
<% end %>
<% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>News Site</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <!--
    <div class="container-fluid py-3 mx-0">
      <div class="d-flex flex-column flex-md-row align-items-center pb-3 mb-4 border-bottom">
        <h5 class="my-0 mr-md-auto fw-bold fs-3"><%= link_to "News Site", home_path, class: "text-decoration-none text-dark" %></h5>
        <nav class="d-inline-flex mt-2 mt-md-0 ms-md-auto">
          <span class="me-3 py-2 link-body-emphasis text-decoration-none"><%= link_to "Головна сторінка", home_path %></span>
          <span class="me-3 py-2 link-body-emphasis text-decoration-none"><%= link_to "Про нас", about_path %></span>
          <span class="me-3 py-2 link-body-emphasis text-decoration-none"><%= link_to "Додавання посту", new_post_path %></span>
        </nav>
      </div>
    </div>
  -->
  <div class="container-fluid py-3 mx-0">
    <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start pb-3 mb-4 border-bottom">
      <h5 class="my-0 mr-md-auto fw-bold fs-3"><%= link_to "News Site", home_path, class: "text-decoration-none text-dark" %></h5>
      <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
        <%= link_to "Головна сторінка", home_path, class: "text-dark me-3", style: "position: relative; top: 3px; left: 16px; text-decoration: none;" %>
        <%= link_to "Про нас", about_path, class: "text-dark me-3", style: "position: relative; top: 3px; left: 16px; text-decoration: none;" %>
        <%= link_to "Додавання посту", new_post_path, class: "text-dark me-3", style: "position: relative; top: 3px; left: 16px; text-decoration: none;" %>
      </ul>
      <div class="text-end">
        <%= render 'include/auth/auth_header' %>
      </div>
    </div>
    <div class="container">
      <%= render 'include/main/notification' %>
    </div>
  </div>
  <div class="container">
    <%= yield %>
  </div>
  </body>
</html>

app/views/pages/about.html.erb
<h2 class="text-dark mb-3"><%= @heading %></h2>
<div class="container-fd">
    <h5 class="text-dark mb-3">Мене звати Смерічка Максим Олексійович.</h5>
    <p>Це простий сайт з постами на різні новинні теми.</p>
    <p>Моя контактна інформація:</p>
    <ul class="list-group mb-3">
        <li class="list-group-item">Електронна пошта: smerichka.maksym@student.uzhnu.edu.ua</li>
        <li class="list-group-item">Номер телефону: +380952265272</li>
    </ul>
    <p>Дякую, що почитали новини на моєму сайті!</p>
</div>

app/views/posts/edit.html.erb
<h2>Редагування посту</h2>
<%= form_for :post, url: post_path(@post), method: :patch do |f| %>
    <% if @post.errors.any? %>
        <% @post.errors.full_messages.each do |msg| %>
            <div class="alert alert-danger"><%= msg %></div>
        <% end %>
    <% end %>
    <% if flash[:error1] %>
        <div class="alert alert-danger">
            <%= flash[:error1] %>
        </div>
    <% end %>
    <% if flash[:error2] %>
        <div class="alert alert-danger">
            <%= flash[:error2] %>
        </div>
    <% end %>
    <p>
        Назва<br>
        <%= f.text_field(:title, {:class => 'form-control'}) %>
    </p>

    <p>
        Текст статті<br>
        <%= f.text_area(:body, {:class => 'form-control'}) %>
    </p>

    <p>
        <%= f.submit "Зберегти пост", ({:class => 'btn btn-success'}) %>
    </p>
<% end %>

app/views/posts/index.html.erb
<h1>Всі наші пости</h1>
<% @post.each do |post| %>
    <div class="alert alert-light">
        <h3 class="text-dark"><%= post.title %></h3>
            <p><%= truncate(post.body, length: 160, omission: '...') %></p>
        <%= link_to "Читати далі...", post_path(post), :class => 'btn btn-outline-primary' %>
    </div>
<% end %>

app/views/posts/new.html.erb
<h2>Додавання нового посту</h2>
<%= form_for :post, url: posts_path do |f| %>
    <% if @post.errors.any? %>
        <% @post.errors.full_messages.each do |msg| %>
            <div class="alert alert-danger"><%= msg %></div>
        <% end %>
    <% end %>
    <% if flash[:error1] %>
        <div class="alert alert-danger">
            <%= flash[:error1] %>
        </div>
    <% end %>
    <% if flash[:error2] %>
        <div class="alert alert-danger">
            <%= flash[:error2] %>
        </div>
    <% end %>
    <p>
        Назва<br>
        <%= f.text_field(:title, {:class => 'form-control'}) %>
    </p>

    <p>
        Текст статті<br>
        <%= f.text_area(:body, {:class => 'form-control'}) %>
    </p>

    <p>
        <%= f.submit 'Зберегти пост', ({:class => 'btn btn-success'}) %>
    </p>
<% end %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<p><%= @post.body %></p>
<hr>
<%= link_to "Редагувати", edit_post_path(@post), :class => 'btn btn-warning' %>
<%= link_to "Видалити", post_path(@post), data: {turbo_method: :delete, turbo_confirm: "Хочете видалити статтю?"}, class: 'btn btn-danger' %>
<hr>
<h2>Всі коментарі</h2>
<% @post.comments.each do |comment| %>
  <div class="alert alert-light">
    <p><strong><%= comment.username %></strong>: <%= comment.body %></p>
    <%= link_to "Редагувати", edit_post_comment_path(@post, comment), :class => 'btn btn-warning' %>
    <%= link_to "Видалити", [@post, comment], data: {turbo_method: :delete, turbo_confirm: "Хочете видалити коментар?"}, :class => 'btn btn-danger' %>
  </div>
<% end %>
<hr>
<h2>Додавання коментаря</h2>
<%= form_for([@post, @post.comments.build]) do |f| %>
  <p>
    Користувач<br>
    <%= f.text_field(:username, {:class => 'form-control'}) %>
  </p>

  <p>
    Текст коментаря<br>
    <%= f.text_area(:body, {:class => 'form-control'}) %>
  </p>

  <p>
    <%= f.submit "Додати коментар", :class => 'btn btn-warning' %>
  </p>
<% end %>